#!/bin/sh
active_window=`xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | awk {'print $2'}`

timestamp="$(date +%Y%m%d%H%M%S)"
targetbase="$HOME/capscr"
mkdir -p $targetbase
[ -d $targetbase ] || exit 1

import -quality 1 -window $active_window $targetbase/$timestamp.png
